apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shashbanexpressjs 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shashbanexpressjs 
    spec:
      containers:
        - name: shashbanexpressjs 
          image: azootestingacr.azurecr.io/shashbanexpressjs 
          ports:
          - containerPort: 3000