apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: expressapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: expressapp
    spec:
      containers:
      - name: expressapp
        image:  atulmakshelm.azurecr.io/express-aks:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: atulmakshelm-auth
