apiVersion: v1
kind: Service
metadata:
    name: {{}} # Data would be extracted from docker registry endpoint
spec:
    type: LoadBalancer
    ports:
    - port: {{ servicePort }} 
    selector:
        app: {{}} # Data would be extracted from docker registry endpoint